image:
  pullPolicy: "Always"

proxy:
  external:
    host: "nomad-lab.eu"

ingress:
  enabled: true

app:
  worker: 2

gui:
  debug: true

worker:
  replicas: 1
  routing: "queue"

elastic:
  host: elasticsearch.elasticsearch-7.svc.cluster.local

mongo:
  host: rs0/mongodb-0.mongo.mongodb.svc.cluster.local,mongodb-1.mongo.mongodb.svc.cluster.local,mongodb-2.mongo.mongodb.svc.cluster.local

logstash:
  host: logstash.elk.svc.cluster.local

dbname: nomad_dev_v1

keycloak:
  serverUrl: "https://nomad-lab.eu/fairdi/keycloak/auth/"
  serverExternalUrl: "https://nomad-lab.eu/fairdi/keycloak/auth/"
  passwordSecret: 'nomad-keycloak-password'
  realmName: 'fairdi_nomad_prod'
  clientId: 'nomad_public'
  admin_user_id: '82efac55-6187-408c-8027-b98580c0e1c5'

volumes:
  prefixSize: 1
  public: /nomad/fairdi/dev/v1/fs/public
  staging: /nomad/fairdi/dev/v1/fs/staging
  tmp: /nomad/fairdi/dev/v1/fs/tmp
  nomad: /nomad
