# default installed image for docker executor is: python:3.5
image: python:3.6

stages:
  - qa
  - test

before_script:
  - pip install virtualenv
  - virtualenv -p `which python3` .pyenv
  - source .pyenv/bin/activate
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - pip install -e .

linting:
  stage: qa
  script:
    - echo "Hello World"

tests:
  stage: test
  services:
      # this will cause a warning, as the gitlab ci runner health check will test the wrong
      # port on rabbitmq container:
      # https://gitlab.com/gitlab-org/gitlab-runner/issues/3163
    - rabbitmq
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
      alias: elastic
      # fix issue with running elastic in gitlab ci runner:
      # https://gitlab.com/gitlab-org/gitlab-ce/issues/42214
      command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]
    - mongo:latest
  variables:
    RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
    RABBITMQ_DEFAULT_USER: rabbitmq
    RABBITMQ_DEFAULT_PASS: rabbitmq
    RABBITMQ_DEFAULT_VHOST: /
    NOMAD_RABBITMQ_HOST: rabbitmq
    NOMAD_ELASTIC_HOST: elastic
    NOMAD_MONGO_HOST: mongo
  script:
    - pip install -r requirements-dep.txt
    - rm -rf .dependencies
    - python nomad/dependencies.py
    - pytest -sv tests/
  only:
    - test_ci
  tags:
    - docker
