# default installed image for docker executor is: python:3.5
# uncomment next line and change as you wish if a different image is needed
image: python:3.6

# additional services needed, the versions are matching the production machine
# the services will be accessible under the hostnames: "postgres" and "mongo"
# services:
#   - rabbitmq
#   - docker.elastic.co/elasticsearch/elasticsearch:6.3.2
#   - mongo:latest

variables:
  NOMAD_RABBIT_HOST: rabbitmq
  NOMAD_ELASTIC_HOST: docker.elastic.co-elasticsearch-elasticsearch
  NOMAD_MONGO_HOST: mongo

stages:
  - test

unittests:
  stage: test
  script:
    - pwd
    - pip install virtualenv
    - rm -rf .pyenv
    - virtualenv -p `which python3` .pyenv
    - source .pyenv/bin/activate
    - pip install -r requirements-dev.txt
    - pip install -r requirements-dep.txt
    - rm -rf .dependencies
    - python nomad/dependencies.py
    - pip install -r requirements.txt
    - pip install -e .
    - pytest -sv tests/
  only:
    - test_ci
  tags:
    - docker
