# default installed image for docker executor is: python:3.6
image: docker:git
services:
  - docker:dind

stages:
  - build
  - test
  - qa

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de

build:
  stage: build
  script:
    - docker build -t gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair:latest .
    - docker push gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair:latest

linting:
  stage: qa
  image: gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair:latest
  script:
    - python -m pycodestyle --ignore=E501,E701 nomad tests
    - python -m pylint --load-plugins=pylint_mongoengine nomad tests
    - python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional nomad tests

tests:
  stage: test
  image: gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair:latest
  services:
      # this will cause a warning, as the gitlab ci runner health check will test the wrong
      # port on rabbitmq container:
      # https://gitlab.com/gitlab-org/gitlab-runner/issues/3163
    - rabbitmq
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
      alias: elastic
      # fix issue with running elastic in gitlab ci runner:
      # https://gitlab.com/gitlab-org/gitlab-ce/issues/42214
      command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]
    - mongo:latest
  variables:
    RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
    RABBITMQ_DEFAULT_USER: rabbitmq
    RABBITMQ_DEFAULT_PASS: rabbitmq
    RABBITMQ_DEFAULT_VHOST: /
    NOMAD_RABBITMQ_HOST: rabbitmq
    NOMAD_ELASTIC_HOST: elastic
    NOMAD_MONGO_HOST: mongo
  script:
    - python -m pytest --cov=nomad -sv tests
