apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomad-api-deployment
  labels:
    app: nomad-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nomad-api
  template:
    metadata:
      labels:
        app: nomad-api
    spec:
      containers:
      - name: nomad-api
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair:latest
        ports:
        - containerPort: 8080