## Default values for nomad@FAIRDI

## Everything concerning the container images to be used
images:
  ## The kubernetes docker-registry secret that can be used to access the registry
  #  with the container image in it.
  #  It can be created via:
  #    kubectl create secret docker-registry gitlab-mpcdf --docker-server=gitlab-registry.mpcdf.mpg.de --docker-username=<your-user-name > --docker-password=<yourpass> --docker-email=<email>
  secret: gitlab-mpcdf

  ## The nomad image with all nomad relavant python code. Used by api and worker service.
  nomad:
    ## The docker container image name without tag
    name: gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair
    ## The docker container image tag
    tag: latest
    pullPolicy: IfNotPresent

## Everthing concerning the nomad api
api:
  replicas: 1
  port: 8000
  console_loglevel: INFO
  logstash_loglevel: INFO
  service_type: ClusterIP
  ## Secret used as cryptographic seed
  secret: "defaultApiSecret"

## Everthing concerning the nomad worker
worker:
  replicas: 2
  console_loglevel: INFO
  logstash_loglevel: INFO

## configuration of the chart dependency for rabbitmq
rabbitmq:
  image.pullSecrets: nil
  rbacEnabled: false
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    erlangCookie: SWQOKODSQALRPCLNMEQG
    plugins: |-
      [].
    configuration: |-
  persistence:
    enabled: false

mongo:
  host: enc-preprocessing-nomad.esc
  port: 37017

elastic:
  host: enc-preprocessing-nomad.esc
  port: 19200

postgres:
  host: enc-preprocessing-nomad.esc
  port: 5432

logstash:
  port: 15000
  host: enc-preprocessing-nomad.esc

## Everything concerning the data that is used by the service
volumes:
  files: /nomad/nomadlab/nomad-FAIRDI/files
