## Default values for nomad@FAIRDI

## Everything concerning the container images to be used
images:
  ## The kubernetes docker-registry secret that can be used to access the registry
  #  with the container image in it.
  #  It can be created via:
  #    kubectl create secret docker-registry gitlab-mpcdf --docker-server=gitlab-registry.mpcdf.mpg.de --docker-username=<your-user-name > --docker-password=<yourpass> --docker-email=<email>
  secret: gitlab-mpcdf

  ## The nomad image with all nomad relavant python code. Used by api and worker service.
  nomad:
    ## The docker container image name without tag
    name: gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair
    ## The docker container image tag
    tag: latest
    pullPolicy: IfNotPresent

  ## The nomad frontend image
  frontend:
    ## The docker container image name without tag
    name: gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair/frontend
    ## The docker container image tag
    tag: latest
    pullPolicy: IfNotPresent

## Everthing concerning the nomad api
api:
  replicas: 1
  https: true
  ## Number of gunicorn worker. Recommendation is 2xnum_cores+1
  worker: 10
  port: 8000
  console_loglevel: INFO
  logstash_loglevel: INFO
  ## Secret used as cryptographic seed
  secret: "defaultApiSecret"
  ## The adminstrator password (only way to ever set/change it)
  adminPassword: "password"
  ## Disable the dangerous reset (delete all data) function
  disableReset: "true"
  ## Limit of unpublished uploads per user, except admin user
  uploadLimit: 10

## Everything concerning the nomad worker
worker:
  replicas: 1
  # request and limit in GB
  memrequest: 64
  memlimit: 420
  console_loglevel: ERROR
  logstash_loglevel: INFO
  ## There are two routing modes "queue" and "worker". The "queue" routing will use a general
  # task queue and spread calc processing task over worker instances. The "worker" routing
  # will send all tasks related to an upload to the same worker
  routing: "queue"
  storage: "disk"

## Everthing concerning the nomad gui
gui:
  replicas: 1
  ## This port is hard coded into the frontend image, it cannot be really changed
  port: 8080
  ## This variable is used in the GUI to show or hide additional information
  debug: false
  ## URL for matomo(piwik) user tracking
  matomoUrl: 'http://nowhere.no'
  ## site id for matomo(piwik) user tracking
  matomoSiteId: 1
  ## send matomo(piwik) user tracking data
  sendTrackingData: false

## Everything concerning the proxy that combined gui, api, kibana
#  It is run via NodePort service
proxy:
  port: 80
  nodePort: 30001
  nodeIP: 130.183.207.104
  timeout: 600
  datatimeout: 3600
  external:
    host: "labdev-nomad.esc.rzg.mpg.de"
    port: 80
    path: "/fairdi/nomad/latest"
    kibanaPath: "/fairdi/kibana"

## configuration of the chart dependency for rabbitmq
rabbitmq:
  persistence:
    enabled: false
  nodeSelector:
    nomadtype: public
  image.pullSecrets: nil
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    erlangCookie: SWQOKODSQALRPCLNMEQG

## A common name/prefix for all dbs and indices.
dbname: fairdi_nomad_latest

## The url for the upload page, used in emails to forward the user
uploadurl: 'https://labdev-nomad.esc.mpg.rzg.de/fairdi/nomad/latest/uploads'

## Databases that are not run within the cluster.
#  To run databases in the cluster, use the nomad-full helm chart.
mongo:
  host: nomad-flink-01.esc
  port: 27017

elastic:
  host: nomad-flink-01.esc
  port: 9200

postgres:
  sequential_publish: false
  publish_enabled: true
  host: nomad-flink-01.esc
  port: 5432
  ## CoE repository mode, values are fairdi, coe. Fairdi stores raw-file path for
  # new raw-file API; coe stores raw-file paths for extracted raw-file copy
  mode: fairdi

logstash:
  port: 5000
  host: nomad-flink-01.esc

kibana:
  port: 5601
  host: nomad-flink-01.esc

mail:
  enabled: "false"
  host: 'localhost'
  port: 25
  from: 'webmaster@nomad-repository.eu'

## Everything concerning the data that is used by the service
volumes:
  prefixSize: 2
  public: /nomad/fairdi/latest/fs/public
  staging: /nomad/fairdi/latest/fs/staging
  tmp: /nomad/fairdi/latest/fs/tmp
  nomad: /nomad

## Everything else
# The domain configuration, currently there is DFT and EMS
domain: DFT
