proxy:
  nodePort: 30014
  timeout: 3600
  external:
    host: "labdev-nomad.esc.rzg.mpg.de"
    path: "/fairdi/nomad/prod-test"

gui:
  debug: true

worker:
  replicas: 1
  routing: "queue"

elastic:
  port: 9202

dbname: fairdi_nomad_prod_v0_7

uploadurl: 'https://labdev-nomad.rzg.mpg.de/fairdi/nomad/prod-test/upload'

keycloak:
  serverUrl: "https://repository.nomad-coe.eu/fairdi/keycloak/auth/"
  passwordSecret: 'nomad-keycloak-password'
  realmName: 'fairdi_nomad_prod'
  clientId: 'nomad_api_dev'
  clientSecret: 'nomad-keycloak-prod-api-secret'
  admin_user_id: '82efac55-6187-408c-8027-b98580c0e1c5'

volumes:
  prefixSize: 1
  public: /nomad/fairdi/prod/fs/public
  staging: /nomad/fairdi/prod/fs/staging
  tmp: /nomad/fairdi/prod/fs/tmp
  nomad: /nomad
