proxy:
  nodePort: 30009
  external:
    host: "labdev-nomad.esc.rzg.mpg.de"
    path: "/fairdi/nomad/testing-major"

gui:
  debug: true

worker:
  replicas: 1
  routing: "queue"
 
elastic:
  port: 9202

dbname: fairdi_nomad_testing_major

uploadurl: 'https://labdev-nomad.rzg.mpg.de/fairdi/nomad/testing-major/upload'

keycloak:
  serverUrl: 'http://130.183.207.104:8002/fairdi/keycloak/auth/'   
  passwordSecret: 'nomad-keycloak-password'
  realmName: 'fairdi_nomad_test'
  clientId: 'nomad_api_dev'
  clientSecret: 'nomad-keycloak-test-api-secret'
  admin_user_id: 'c97facc2-92ec-4fa6-80cf-a08ed957255b'

volumes:
  prefixSize: 1
  public: /nomad/fairdi/testing_major/fs/public
  staging: /nomad/fairdi/testing_major/fs/staging
  tmp: /nomad/fairdi/testing_major/fs/tmp
  nomad: /nomad
