proxy:
  nodePort: 30014
  external:
    host: "labdev-nomad.esc.rzg.mpg.de"
    path: "/fairdi/nomad/prod-test"

api:
  adminPasswordSecret: 'nomad-production-repository-password'

gui:
  debug: true

worker:
  replicas: 1
  routing: "queue"

dbname: fairdi_nomad_prod

uploadurl: 'https://labdev-nomad.rzg.mpg.de/fairdi/nomad/prod-test/upload'

keycloak:
  passwordSecret: 'nomad-keycloak-password'
  clientSecret: 'nomad-keycloak-prod-api-secret'

volumes:
  prefixSize: 1
  public: /nomad/fairdi/prod/fs/public
  staging: /nomad/fairdi/prod/fs/staging
  tmp: /nomad/fairdi/prod/fs/tmp
  nomad: /nomad
