apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nomad.fullname" . }}-gui-config
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-gui-config
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
    server {
      listen        8080;
      server_name   www.example.com;
      location {{ .Values.proxy.external.path }}/gui {
        root      /app/;
        rewrite ^{{ .Values.proxy.external.path }}/gui/(.*)$ /nomad/$1 break;
        try_files $uri {{ .Values.proxy.external.path }}/gui/index.html;
      }
      location {{ .Values.proxy.external.path }}/gui/service-worker.js {
        add_header Cache-Control "public, max-age=60, s-maxage=60";
        expires -1;
        root      /app/;
        rewrite ^{{ .Values.proxy.external.path }}/gui/service-worker.js /nomad/service-worker.js break;
      }
    }
  env.js: |
    window.nomadEnv = {
      "apiBase": "{{ .Values.proxy.external.path }}/api",
      "kibanaBase": "{{ .Values.proxy.external.kibanaPath }}",
      "matomoSiteId": {{ .Values.gui.matomoSiteId }},
      "matomoUrl": {{ .Values.gui.matomoUrl }},
      "sendTrackingData": {{ .Values.gui.sendTrackingData }},
      "debug": {{ .Values.gui.debug }}
    };
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nomad.fullname" . }}-gui
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-gui
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.gui.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nomad.name" . }}-gui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nomad.name" . }}-gui
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "nomad.name" . }}-gui
        image: "{{ .Values.images.frontend.name }}:{{ .Values.images.frontend.tag }}"
        command: ["./run.sh",  "{{ .Values.proxy.external.path }}"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-conf
        - mountPath: /app/nomad/env.js
          readOnly: true
          subPath: env.js
          name: nomad-app
        - mountPath: /var/log/nginx
          name: log
        livenessProbe:
          httpGet:
            path: "{{ .Values.proxy.external.path }}/gui/index.html"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: "{{ .Values.proxy.external.path }}/gui/index.html"
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
      nodeSelector:
        nomadtype: public
      imagePullSecrets:
      - name: {{ .Values.images.secret }}
      imagePullPolicy: always
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "nomad.fullname" . }}-gui-config
          items:
          - key: nginx.conf
            path: default.conf
      - name: nomad-app
        configMap:
          name: {{ include "nomad.fullname" . }}-gui-config
          items:
          - key: env.js
            path: env.js
      - name: log
        emptyDir: {}
