apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nomad.fullname" . }}-gui-config
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-gui-config
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
    server {
      listen        80;
      server_name   www.example.com;
      proxy_set_header Host $host;

      proxy_connect_timeout {{ .Values.proxy.timeout }};
      proxy_read_timeout {{ .Values.proxy.timeout }};

      location / {
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ {{ .Values.proxy.external.path }}\/?(gui)?$ {
        rewrite ^ {{ .Values.proxy.external.path }}/gui/ permanent;
      }

      location {{ .Values.proxy.external.path }}/gui/ {
        proxy_intercept_errors on;
        error_page 404 = @redirect_to_index;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location @redirect_to_index {
        rewrite ^ {{ .Values.proxy.external.path }}/gui/index.html break;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ \/gui\/(service-worker\.js|meta\.json)$ {
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ \/api\/uploads\/?$ {
        client_max_body_size 35g;
        proxy_request_buffering off;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ \/api\/(raw|archive) {
        proxy_buffering off;
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }

      location ~ \/api\/mirror {
        proxy_buffering off;
        proxy_read_timeout {{ .Values.proxy.mirrorTimeout }};
        proxy_pass http://{{ include "nomad.fullname" . }}-app:8000;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nomad.fullname" . }}-gui
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-gui
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.gui.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nomad.name" . }}-gui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nomad.name" . }}-gui
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{ if .Values.roll }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
    spec:
      containers:
      - name: {{ include "nomad.name" . }}-gui
        image: "nginx:1.13.9-alpine"
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
        livenessProbe:
          httpGet:
            path: "{{ .Values.proxy.external.path }}/gui/index.html"
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: "{{ .Values.proxy.external.path }}/gui/index.html"
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
      nodeSelector:
        nomadtype: public
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "nomad.fullname" . }}-gui-config
          items:
          - key: nginx.conf
            path: default.conf
      - name: log
        emptyDir: {}
