apiVersion: v1
kind: Service
metadata:
  name: {{ include "nomad.fullname" . }}-gui
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-gui
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gui.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-gui
    app.kubernetes.io/instance: {{ .Release.Name }}
