apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nomad.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-configmap
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nomad.yaml: |
    release: "{{ .Release.Name }}"
    domain: "{{ .Values.domain }}"
    fs:
      tmp: "{{ .Values.volumes.tmp }}"
      prefix_size: {{ .Values.volumes.prefixSize }}
      working_directory: /app
    logstash:
      enabled: true
      host: "{{ .Values.logstash.host }}"
      tcp_port: {{ .Values.logstash.port }}
    services:
      api_host: "{{ .Values.proxy.external.host }}"
      api_port: {{ .Values.proxy.external.port }}
      api_base_path: "{{ .Values.proxy.external.path }}"
      api_secret: "{{ .Values.api.secret }}"
      https: {{ .Values.app.https }}
      upload_limit: {{ .Values.api.uploadLimit }}
    rabbitmq:
      host: "{{ .Release.Name }}-rabbitmq"
    elastic:
      host: "{{ .Values.elastic.host }}"
      port: {{ .Values.elastic.port }}
      index_name: "{{ .Values.dbname }}"
    mongo:
      host: "{{ .Values.mongo.host }}"
      port: {{ .Values.mongo.port }}
      db_name: "{{ .Values.dbname }}"
    mail:
      enabled: {{ .Values.mail.enabled }}
      host: "{{ .Values.mail.host }}"
      {{ if .Values.mail.port }}
      port: {{ .Values.mail.port }}
      {{ end }}
      {{ if .Values.mail.user }}
      user: "{{ .Values.mail.user }}"
      {{ end }}
      {{ if .Values.mail.password }}
      password: "{{ .Values.mail.password }}"
      {{ end }}
      from_address: "{{ .Values.mail.from }}"
    celery:
      routing: "{{ .Values.worker.routing }}"
      timeout: 7200
    keycloak:
      server_url: "{{ .Values.keycloak.serverUrl }}"
      realm_name: "{{ .Values.keycloak.realmName }}"
      username: "{{ .Values.keycloak.username }}"
      client_id: "{{ .Values.keycloak.clientId }}"
      client_secret: "*"
      password: "*"
