apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nomad.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-configmap
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nomad.yaml: |
    release: "{{ .Release.Name }}"
    domain: "{{ .Values.domain }}"
    fs:
      tmp: "{{ .Values.volumes.tmp }}"
      prefix_size: {{ .Values.volumes.prefixSize }}
      working_directory: /app
    logstash:
      enabled: true
      host: "{{ .Values.logstash.host }}"
      tcp_port: {{ .Values.logstash.port }}
    services:
      api_host: "{{ .Values.proxy.external.host }}"
      api_port: {{ .Values.proxy.external.port }}
      api_base_path: "{{ .Values.proxy.external.path }}/api"
      api_secret: "{{ .Values.api.secret }}"
      admin_password: "{{ .Values.api.adminPassword }}"
      disable_reset: {{ .Values.api.disableReset }}
      https: {{ .Values.api.https }}
      upload_limit: {{ .Values.api.uploadLimit }}
    rabbitmq:
      host: "{{ .Release.Name }}-rabbitmq"
    elastic:
      host: "{{ .Values.elastic.host }}"
      port: {{ .Values.elastic.port }}
      index_name: "{{ .Values.dbname }}"
    mongo:
      host: "{{ .Values.mongo.host }}"
      port: {{ .Values.mongo.port }}
      db_name: "{{ .Values.dbname }}"
    repository_db:
      host: "{{ .Values.postgres.host }}"
      port: {{ .Values.postgres.port }}
      dbname: {{ if .Values.postgres.dbname }} "{{ .Values.postgres.dbname }}" {{ else }} "{{ .Values.dbname }}" {{ end }}
      sequential_publish: {{ .Values.postgres.sequential_publish }}
      publish_enabled: {{ .Values.postgres.publish_enabled }}
      mode: "{{ .Values.postgres.mode }}"
      {{ if .Values.postgres.user }}
      user: "{{ .Values.postgres.user }}"
      {{ end }}
      {{ if .Values.postgres.password }}
      password: "{{ .Values.postgres.password }}"
      {{ end }}
    mail:
      host: "{{ .Values.mail.host }}"
      port: {{ .Values.mail.port }}
      user: "{{ .Values.mail.user }}"
      password: "{{ .Values.mail.password }}"
      from_address: "{{ .Values.mail.from }}"
    celery:
      routing: "{{ .Values.worker.routing }}"
      timeout: 7200

