apiVersion: v1
kind: Service
metadata:
  name: {{ include "nomad.fullname" . }}-proxy
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-proxy
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  externalIPs:
  - 130.183.207.116 
  ports:
  - nodePort: {{ .Values.proxy.nodePort }}
    port: {{ .Values.proxy.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
