apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongodb
spec:
  selector:
    matchLabels:
      role: mongo
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: mongo
                app.kubernetes.io/instance: mongo
      nodeSelector:
        infratype: db
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4
        command:
          - mongod
          - "--bind_ip"
          - "0.0.0.0"
          - "--replSet"
          - rs0
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: storage
            mountPath: /data/db
      volumes:
      - name: storage
        hostPath:
          path: /scratch/fairdi/db/mongo
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
  labels:
    name: mongo
spec:
  selector:
    role: mongo
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-external
  namespace: mongodb
  labels:
    name: mongo-external
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mongo-0
  type: NodePort
  externalIPs: 
  - 130.183.207.104
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30217
    protocol: TCP
