apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nomad.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "nomad.name" . }}-worker
    helm.sh/chart: {{ include "nomad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nomad.name" . }}-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nomad.name" . }}-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "nomad.name" . }}-worker
        image: "{{ .Values.images.nomad.name }}:{{ .Values.images.nomad.tag }}"
        volumeMounts:
        - mountPath: /app/.volumes/fs
          name: files-volume
        env:
        - name: NOMAD_SERVICE
          value: "worker"
        - name: NOMAD_LOGSTASH_HOST
          value: {{ .Values.logstash.host }}
        - name: NOMAD_LOGSTASH_TCPPORT
          value: {{ .Values.logstash.port }}
        - name: NOMAD_CONSOLE_LOGLEVEL
          value: {{ .Values.worker.console_loglevel }}
        - name: NOMAD_LOGSTASH_LEVEL
          value: {{ .Values.worker.logstash_loglevel }}
      imagePullSecrets:
      - name: {{ .Values.images.secret }}
      volumes:
      - name: files-volume
        hostPath:
          path: {{ .Values.volumes.files }}
          type: Directory
