# Copyright 2018 Markus Scheidgen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an"AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.4'

services:
    # keycloak for user management
    keycloak:
        environment:
            - DB_VENDOR=h2

    # broker for celery
    rabbitmq:
        restart: 'no'
        ports:
            - 5672:5672

    # the search engine
    elastic:
        restart: 'no'
        ports:
            - 9200:9200

    # the user data db
    mongo:
        restart: 'no'
        ports:
            - 27017:27017

    # nomad processing worker
    worker:
        restart: 'no'
        build: ../../../
        image: nomad/backend

    # nomad app
    app:
        restart: 'no'
        image: nomad/backend
        depends_on:
            - worker
        ports:
            - 8000:8000

    # nomad gui
    gui:
        restart: 'no'
        build: ../../../gui
        image: nomad/frontend
        ports:
            - 8080:8000
