version: '3'

services:
  minio:
    restart: always
    image: minio/minio:RELEASE.2018-06-08T03-49-38Z
    # image: minio/minio
    ports:
      - 9007:9000
    volumes:
      - ./data/minio:/data
      - ./config/minio:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    command: server /data
    # links:
    #   - rabbitmq

  # rabbitmq:
  #   image: rabbitmq
  #   hostname: "rabbitmq"
  #   environment:
  #     - "RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG"
  #     - "RABBITMQ_DEFAULT_USER=rabbitmq"
  #     - "RABBITMQ_DEFAULT_PASS=rabbitmq"
  #     - "RABBITMQ_DEFAULT_VHOST=/"
  #   ports:
  #     - 5672:5672
